// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelDistributionCenter.Model.Context;

#nullable disable

namespace ParcelDistributionCenter.Web.Migrations
{
    [DbContext(typeof(ParcelDistributionCenterContext))]
    [Migration("20230610100422_ReportPackageEntityAdded")]
    partial class ReportPackageEntityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.Courier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeliveryMachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMachineId")
                        .IsUnique()
                        .HasFilter("[DeliveryMachineId] IS NOT NULL");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.DeliveryMachine", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BigLockersCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MediumLockersCount")
                        .HasColumnType("int");

                    b.Property<int>("SmallLockersCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMachines");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.Package", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryMachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PackageNumber")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("DeliveryMachineId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.ReportPackage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AddingDurationInSeconds")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReportPackages");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.Courier", b =>
                {
                    b.HasOne("ParcelDistributionCenter.Model.Entites.DeliveryMachine", "DeliveryMachine")
                        .WithOne("Courier")
                        .HasForeignKey("ParcelDistributionCenter.Model.Entites.Courier", "DeliveryMachineId");

                    b.Navigation("DeliveryMachine");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.Package", b =>
                {
                    b.HasOne("ParcelDistributionCenter.Model.Entites.Courier", "Courier")
                        .WithMany("Packages")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ParcelDistributionCenter.Model.Entites.DeliveryMachine", "DeliveryMachine")
                        .WithMany("Packages")
                        .HasForeignKey("DeliveryMachineId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Courier");

                    b.Navigation("DeliveryMachine");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.Courier", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("ParcelDistributionCenter.Model.Entites.DeliveryMachine", b =>
                {
                    b.Navigation("Courier")
                        .IsRequired();

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
